version: '3'
services:
  app:
    image: ghcr.io/ubccsss/blood-for-life-api
    ports:
      - 1323:1323
  db:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
