name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      # Setup qemu to generate both arm and x86 images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      # Setup build 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64, linux/arm64, darwin/amd64
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:cache
          cache-to: type=inline
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
